In [1]:

import numpy as np #used for mathatical operations what it do it is in c++ it compiled to python then run the output which make it faster than python list as it is not in python

In [5]:
#python list 
ar1=list(range(100000))
ar2=list(range(100000,2000000))


In [6]:
%%time
result=0
for x1,x2 in zip(ar1,ar2):
    result+=x1*x2
result

Wall time: 26 ms


833323333350000

In [11]:
#with numpy function .dot multiply elements of two arrays

#numpy arrays
arr1_n=np.array(ar1)
arr2_n=np.array(ar2)

np.dot(arr1_n,arr2_n)

ValueError: shapes (100000,) and (1900000,) not aligned: 100000 (dim 0) != 1900000 (dim 0)

In [20]:
#multi dimensional array in nupy there is list of apples produced per hectre i each temratures,rainy,sunlight etc in each list
climate_data=np.array([[73,67,43],
                       [63,68,43],
                       [78,69,21],
                       [23,57,42]])
climate_data

array([[73, 67, 43],
       [63, 68, 43],
       [78, 69, 21],
       [23, 57, 42]])

In [21]:
climate_data.shape #to identify rows and columns in a matrix outpit is tuple

(4, 3)

In [22]:
#3d array
arr3=np.array([[[1,2,3],[4,6,7]],
               [[8,9,10],[11,12,13]]])
arr3

array([[[ 1,  2,  3],
        [ 4,  6,  7]],

       [[ 8,  9, 10],
        [11, 12, 13]]])

In [23]:
arr3.shape# (2,2,3) 2 rows in each list in 3d array and each list have  3 column


(2, 2, 3)

In [24]:
arr3.dtype

dtype('int32')

In [25]:
climate_data.dtype # all numpy elements array should be of same data type numpy has its own datatype as compared to python which has vast primitative datatypes 


dtype('int32')

In [26]:
#3d array
#In nmpy array if anyone of the eement is in float and rest of are in int than all will convert to float if any one them is float
arr3=np.array([[[1,2,3],[4,6,7]],
               [[8,9,10],[11,12,13.6]]])
arr3.dtype

dtype('float64')

In [28]:
#Now matrix multiplication w1,w2,w3 is the weights of each apple produced per hactre 
weights=[0.3,0.4,0.5]
#climate data of each region temprature,rainy,humidityseason apples produced
#now for matrix multiplication to take out total sum of apples produced in each region on the absis of per hactre
np.matmul(climate_data,weights)

array([70.2, 67.6, 61.5, 50.7])

In [29]:
#Anoher way of matrix multiplication
climate_data @ weights

array([70.2, 67.6, 61.5, 50.7])

In [40]:
#now numpy in  txt
f = open("weather.txt", "r")
print(f)

<_io.TextIOWrapper name='weather.txt' mode='r' encoding='cp1252'>


In [41]:
#used when file is in txt
data=np.genfromtxt(f,delimiter=',',skip_header=1)

In [42]:
data

array([[23., 56., 78.],
       [33., 56., 78.],
       [23., 56., 78.],
       [12., 23., 45.],
       [76., 98., 67.]])

In [43]:
data.shape


(5, 3)

In [44]:
weigh=np.array([0.3,0.4,0.5])

In [47]:
#each row calculation is made of yield per hactre
yields=data @ weigh
yields

array([68.3, 71.3, 68.3, 35.3, 95.5])

In [49]:
yields.shape#total number of output

(5,)

In [57]:
#adding that new yild column now with numpy axis is 1 beacuse we just adding one more yield element in each list
climate_results=np.concatenate((data,yields.reshape(5,1)),axis=1)
climate_results

array([[23. , 56. , 78. , 68.3],
       [33. , 56. , 78. , 71.3],
       [23. , 56. , 78. , 68.3],
       [12. , 23. , 45. , 35.3],
       [76. , 98. , 67. , 95.5]])

In [60]:
#now writing the new data to file
np.savetxt('weather.txt',climate_results,fmt='%.2f',header='Temprature,Rainy,humidity,yield',comments=' ')

In [67]:
#mean function in numpy
n1=np.array([[73,67,43],
                       [63,68,43],
                       [78,69,21],
                       [23,57,42]])

np.mean(n1)

53.916666666666664

In [69]:
#median 
n2=np.array([[79,64,32],
                       [13,98,83],
                       [78,60,11],
                       [33,37,92]])
np.median(n2)

62.0

In [72]:
n1>n2

array([[False,  True,  True],
       [ True, False, False],
       [False,  True,  True],
       [False,  True, False]])

In [76]:
#calcuate that how much values of n1 array are greater than n2
(n1>n2).sum()

6

In [77]:
n1==n2

array([[False, False, False],
       [False, False, False],
       [ True, False, False],
       [False, False, False]])

In [80]:
np.std(n1)

18.377787014642312

In [79]:
np.var(n1)

337.7430555555556