In [1]:
import tensorflow as tf

In [2]:
print(tf.version)

<module 'tensorflow._api.v2.version' from 'C:\\Python\\lib\\site-packages\\tensorflow\\_api\\v2\\version\\__init__.py'>


In [3]:
#What are tensors?
#A tensor is a container for numerical data. It is the way we store the information that we'll use within our system

In [4]:
#Creating Tensors and thier datatypes
string = tf.Variable("this is a string", tf.string) #this will be ranked 0 becaue it has only 1 but when we have an array it will rank according to array elements 1,2,3,4 means we have more than 1 elemnet in an array
number = tf.Variable(324, tf.int16)                 # tf.string datatype of a tensor
floating = tf.Variable(3.567, tf.float64)
#when we talk about vector value means more than one value
#scalar means one value

In [5]:
#Rank/Degree Of a  Tensor(these terms simply mean the number of dimensions involved in the tensor)
rank1_tensor = tf.Variable(["Test","ok", "yes"], tf.string) #["Test","ok", "yes"] 1 dimension array so it is rank 1
rank2_tensor = tf.Variable([["test", "ok",'done'], ["test", "yes",'done']], tf.string)#[["test", "ok"], ["test", "yes"]] it is list inside list means it is 2 dimensional rank2 tensor

In [6]:
#To determine the rank of a tensor we can call the following method.
tf.rank(rank2_tensor),tf.rank(rank1_tensor)
#numpy=2 means its rank 2 tensor

(<tf.Tensor: shape=(), dtype=int32, numpy=2>,
 <tf.Tensor: shape=(), dtype=int32, numpy=1>)

In [7]:
#The shape of a tensor is simply the number of elements that exist in each dimension. TensorFlow will try to determine the shape of a tensor but sometimes it may be unknown.
rank2_tensor.shape,rank1_tensor.shape
#means it has 2 tensors and each has 3 column and in two dimensional each dimension uniform amount of data for eg [[1,2,3][4,5,6]] it cannot be possible if we write [[1,2,3][4,5]] 

(TensorShape([2, 3]), TensorShape([3]))

In [8]:
#CHANGING THE SHAPE OF TENSORS
tensor1 = tf.ones([1,2,3])  # tf.ones() creates a shape [1,2,3] tensor full of ones
tensor2 = tf.reshape(tensor1, [2,3,1])  # reshape existing data to shape [2,3,1]
tensor3 = tf.reshape(tensor2, [3, -1])  # -1 tells the tensor to calculate the size of the dimension in that place
                                        # this will reshape the tensor to [3,2]
                                                                             
# The numer of elements in the reshaped tensor MUST match the number in the original

In [9]:
print(tensor1)
print(tensor2)
print(tensor3)

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)
tf.Tensor(
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]], shape=(2, 3, 1), dtype=float32)
tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)


In [10]:
Types of Tensors:
Variable can be changed
Constant(immutable) cannot be chnged
Placeholder
SparseTensor

SyntaxError: invalid syntax (1735247362.py, line 1)

In [12]:
#Slicing TENSORS
# Creating a 2D tensor
matrix = [[1,2,3,4,5],
          [6,7,8,9,10],
          [11,12,13,14,15],
          [16,17,18,19,20]]

tensor = tf.Variable(matrix, dtype=tf.int32) 
print(tf.rank(tensor))
print(tensor.shape)

tf.Tensor(2, shape=(), dtype=int32)
(4, 5)


In [13]:
# Now lets select some different rows and columns from our tensor

three = tensor[0,2]  # selects the 3rd element from the 1st row
print(three)  # -> 3



tf.Tensor(3, shape=(), dtype=int32)


In [14]:
row1 = tensor[0]  # selects the first row
print(row1)


tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int32)


In [15]:
column1 = tensor[:, 0]  # selects the first column
print(column1)

tf.Tensor([ 1  6 11 16], shape=(4,), dtype=int32)


In [16]:
row_2_and_4 = tensor[1::2]  # selects second and fourth row
print(row_2_and_4)

tf.Tensor(
[[ 6  7  8  9 10]
 [16 17 18 19 20]], shape=(2, 5), dtype=int32)


In [17]:
column_1_in_row_2_and_3 = tensor[1:3, 0]
print(column_1_in_row_2_and_3)

tf.Tensor([ 6 11], shape=(2,), dtype=int32)


In [19]:
t=tf.ones([5,5,5,5])
print(t)

tf.Tensor(
[[[[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]]


 [[[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1.