### All Techniques Of Hyper Parameter Optimization

1. GridSearchCV
2. RandomizedSearchCV
3. Bayesian Optimization -Automate Hyperparameter Tuning (Hyperopt)
4. Sequential Model Based Optimization(Tuning a scikit-learn estimator with skopt)
4. Optuna- Automate Hyperparameter Tuning
5. Genetic Algorithms (TPOT Classifier) #FOR LARGE DATASETS NOT SO COMPATABLE FOR SMALL DATASETS

###### References
- https://github.com/fmfn/BayesianOptimization
- https://github.com/hyperopt/hyperopt
- https://www.jeremyjordan.me/hyperparameter-tuning/
- https://optuna.org/
- https://towardsdatascience.com/hyperparameters-optimization-526348bb8e2d(By Pier Paolo Ippolito )
- https://scikit-optimize.github.io/stable/auto_examples/hyperparameter-optimization.html


In [10]:
import warnings #THIS IS BEACUSE THE WARNINGNS I WAS GETTING IN SOME OF THE MODEL OF SKLEARN
warnings.filterwarninRgs('ignore')

AttributeError: module 'warnings' has no attribute 'filterwarninRgs'

In [11]:
import pandas as pd
df=pd.read_csv('diabetes.csv')
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [12]:
import numpy as np#The numpy. where() function returns the indices of elements in an input array where the given condition is satisfied. Parameters: condition : When True, yield x, otherwise yield y.
df['Glucose']=np.where(df['Glucose']==0,df['Glucose'].median(),df['Glucose'])#LOGICALLY GLUCOSE CANNOT BE 0 SO EHAT WE ARE DOING THAT WHERE EVER GLUCOSD VALUE==0 WE ARE REPLACING IT WITH THE MEDIAN OF THE GLUCOSE COLUMN AND IF ITS NOT 0 THEN WE ARE KEEPING THE SAME VALUE
df['Insulin']=np.where(df['Insulin']==0,df['Insulin'].median(),df['Insulin'])
df['SkinThickness']=np.where(df['SkinThickness']==0,df['SkinThickness'].median(),df['SkinThickness'])
df.head()
#I DIDNT REPLACE WITH MEAN BECAUSE THE OUTLIERS WILL THEN AFFECT OUR PROBLEM

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6    148.0             72           35.0     30.5  33.6   
1            1     85.0             66           29.0     30.5  26.6   
2            8    183.0             64           23.0     30.5  23.3   
3            1     89.0             66           23.0     94.0  28.1   
4            0    137.0             40           35.0    168.0  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [13]:
#### Independent And Dependent features
X=df.drop('Outcome',axis=1)
y=df['Outcome']

In [14]:
pd.DataFrame(X,columns=df.columns[:-1])

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6    148.0             72           35.0     30.5  33.6   
1              1     85.0             66           29.0     30.5  26.6   
2              8    183.0             64           23.0     30.5  23.3   
3              1     89.0             66           23.0     94.0  28.1   
4              0    137.0             40           35.0    168.0  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10    101.0             76           48.0    180.0  32.9   
764            2    122.0             70           27.0     30.5  36.8   
765            5    121.0             72           23.0    112.0  26.2   
766            1    126.0             60           23.0     30.5  30.1   
767            1     93.0             70           31.0     30.5  30.4   

     DiabetesPedigreeFunction  Age  
0                       0.627   50  
1                       0.351   31  
2                       0.672   32  
3                       0.167   21  
4                       2.288   33  
..                        ...  ...  
763                     0.171   63  
764                     0.340   27  
765                     0.245   30  
766                     0.349   47  
767                     0.315   23  

[768 rows x 8 columns]

In [15]:
#### Train Test Split
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.20,random_state=0)

In [16]:
from sklearn.ensemble import RandomForestClassifier
rf_classifier=RandomForestClassifier(n_estimators=10).fit(X_train,y_train)
prediction=rf_classifier.predict(X_test)

In [17]:
y.value_counts()

0    500
1    268
Name: Outcome, dtype: int64

In [18]:
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score
print(confusion_matrix(y_test,prediction))
print(accuracy_score(y_test,prediction))
print(classification_report(y_test,prediction))

[[95 12]
 [22 25]]
0.7792207792207793
              precision    recall  f1-score   support

           0       0.81      0.89      0.85       107
           1       0.68      0.53      0.60        47

    accuracy                           0.78       154
   macro avg       0.74      0.71      0.72       154
weighted avg       0.77      0.78      0.77       154



The main parameters used by a Random Forest Classifier are:

- criterion = the function used to evaluate the quality of a split.
- max_depth = maximum number of levels allowed in each tree.
- max_features = maximum number of features considered when splitting a node.
- min_samples_leaf = minimum number of samples which can be stored in a tree leaf.
- min_samples_split = minimum number of samples necessary in a node to cause node splitting.
- n_estimators = number of trees in the ensamble.

In [20]:
### Manual Hyperparameter Tuning means i am randomly giving the values according to my mood i dont know why i am doing it
model=RandomForestClassifier(n_estimators=300,criterion='entropy',
                             max_features='sqrt',min_samples_leaf=10,random_state=100).fit(X_train,y_train)
predictions=model.predict(X_test)
print(confusion_matrix(y_test,predictions))
print(accuracy_score(y_test,predictions))
print(classification_report(y_test,predictions))

[[97 10]
 [17 30]]
0.8246753246753247
              precision    recall  f1-score   support

           0       0.85      0.91      0.88       107
           1       0.75      0.64      0.69        47

    accuracy                           0.82       154
   macro avg       0.80      0.77      0.78       154
weighted avg       0.82      0.82      0.82       154



##### Randomized Search Cv

In [ ]:
numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)[source]
Return evenly spaced numbers over a specified interval.
np.linspace(2.0, 3.0, num=5)
array([2.  , 2.25, 2.5 , 2.75, 3.  ])

In [21]:
import numpy as np
from sklearn.model_selection import RandomizedSearchCV
# Number of trees in random forest
n_estimators = [int(x) for x in np.linspace(start = 200, stop = 2000, num = 10)]
# Number of features to consider at every split
max_features = ['auto', 'sqrt','log2']
# Maximum number of levels in tree
max_depth = [int(x) for x in np.linspace(10, 1000,10)]
# Minimum number of samples required to split a node
min_samples_split = [2, 5, 10,14]
# Minimum number of samples required at each leaf node
min_samples_leaf = [1, 2, 4,6,8]
# Create the random grid
random_grid = {'n_estimators': n_estimators,
               'max_features': max_features,
               'max_depth': max_depth,
               'min_samples_split': min_samples_split,
               'min_samples_leaf': min_samples_leaf,
              'criterion':['entropy','gini']}
print(random_grid)

{'n_estimators': [200, 400, 600, 800, 1000, 1200, 1400, 1600, 1800, 2000], 'max_features': ['auto', 'sqrt', 'log2'], 'max_depth': [10, 120, 230, 340, 450, 560, 670, 780, 890, 1000], 'min_samples_split': [2, 5, 10, 14], 'min_samples_leaf': [1, 2, 4, 6, 8], 'criterion': ['entropy', 'gini']}


In [22]:
from sklearn.ensemble import RandomForestClassifier
rf=RandomForestClassifier()
rf_randomcv=RandomizedSearchCV(estimator=rf,param_distributions=random_grid,n_iter=100,cv=3,verbose=2,
random_state=100,n_jobs=-1)
### fit the randomized model
rf_randomcv.fit(X_train,y_train)
#in param_distribution u have to provide your random grid that key values that you have set aove (cv is cross validation it is used to  Cross-Validation is a statistical method of evaluating and comparing learning algorithms by dividing data into two segments: one used to learn or train a model and the other used to validate the model.)
 # fitting 3 folds means cv=3 3 segments then random state =300 both are multiplied to obtain total fits    

Fitting 3 folds for each of 100 candidates, totalling 300 fits


RandomizedSearchCV(cv=3, estimator=RandomForestClassifier(), n_iter=100,
                   n_jobs=-1,
                   param_distributions={'criterion': ['entropy', 'gini'],
                                        'max_depth': [10, 120, 230, 340, 450,
                                                      560, 670, 780, 890,
                                                      1000],
                                        'max_features': ['auto', 'sqrt',
                                                         'log2'],
                                        'min_samples_leaf': [1, 2, 4, 6, 8],
                                        'min_samples_split': [2, 5, 10, 14],
                                        'n_estimators': [200, 400, 600, 800,
                                                         1000, 1200, 1400, 1600,
                                                         1800, 2000]},
                   random_state=100, verbose=2)

In [23]:
rf_randomcv.best_params_ #tells us the est possible values for each parameter

{'n_estimators': 1800,
 'min_samples_split': 5,
 'min_samples_leaf': 1,
 'max_features': 'auto',
 'max_depth': 450,
 'criterion': 'gini'}

In [26]:
rf_randomcv 

RandomizedSearchCV(cv=3, estimator=RandomForestClassifier(), n_iter=100,
                   n_jobs=-1,
                   param_distributions={'criterion': ['entropy', 'gini'],
                                        'max_depth': [10, 120, 230, 340, 450,
                                                      560, 670, 780, 890,
                                                      1000],
                                        'max_features': ['auto', 'sqrt',
                                                         'log2'],
                                        'min_samples_leaf': [1, 2, 4, 6, 8],
                                        'min_samples_split': [2, 5, 10, 14],
                                        'n_estimators': [200, 400, 600, 800,
                                                         1000, 1200, 1400, 1600,
                                                         1800, 2000]},
                   random_state=100, verbose=2)

In [29]:
best_random_grid=rf_randomcv.best_estimator_ #tells us best parameters to select out of all and thier values
best_random_grid

RandomForestClassifier(max_depth=450, min_samples_split=5, n_estimators=1800)

In [30]:
from sklearn.metrics import accuracy_score
y_pred=best_random_grid.predict(X_test)
print(confusion_matrix(y_test,y_pred))
print("Accuracy Score {}".format(accuracy_score(y_test,y_pred)))
print("Classification report: {}".format(classification_report(y_test,y_pred)))

[[95 12]
 [14 33]]
Accuracy Score 0.8311688311688312
Classification report:               precision    recall  f1-score   support

           0       0.87      0.89      0.88       107
           1       0.73      0.70      0.72        47

    accuracy                           0.83       154
   macro avg       0.80      0.79      0.80       154
weighted avg       0.83      0.83      0.83       154



#### GridSearch CV

In [31]:
rf_randomcv.best_params_

{'n_estimators': 1800,
 'min_samples_split': 5,
 'min_samples_leaf': 1,
 'max_features': 'auto',
 'max_depth': 450,
 'criterion': 'gini'}

In [32]:
from sklearn.model_selection import GridSearchCV

param_grid = {
    'criterion': [rf_randomcv.best_params_['criterion']],
    'max_depth': [rf_randomcv.best_params_['max_depth']],
    'max_features': [rf_randomcv.best_params_['max_features']],
    'min_samples_leaf': [rf_randomcv.best_params_['min_samples_leaf'], 
                         rf_randomcv.best_params_['min_samples_leaf']+2, 
                         rf_randomcv.best_params_['min_samples_leaf'] + 4],
    'min_samples_split': [rf_randomcv.best_params_['min_samples_split'] - 2,
                          rf_randomcv.best_params_['min_samples_split'] - 1,
                          rf_randomcv.best_params_['min_samples_split'], 
                          rf_randomcv.best_params_['min_samples_split'] +1,
                          rf_randomcv.best_params_['min_samples_split'] + 2],
    'n_estimators': [rf_randomcv.best_params_['n_estimators'] - 200, rf_randomcv.best_params_['n_estimators'] - 100, 
                     rf_randomcv.best_params_['n_estimators'], 
                     rf_randomcv.best_params_['n_estimators'] + 100, rf_randomcv.best_params_['n_estimators'] + 200]
}

print(param_grid)

{'criterion': ['gini'], 'max_depth': [450], 'max_features': ['auto'], 'min_samples_leaf': [1, 3, 5], 'min_samples_split': [3, 4, 5, 6, 7], 'n_estimators': [1600, 1700, 1800, 1900, 2000]}


In [34]:
#grid cv iterate and it happens on the basis of no of parameters we selected foreg criterion has 1, max depth has 1, min sample leaf has 3 ,estimators has 5
#so it will multiply all the no of parameters inside each parameter like this:
1*1*1*3*5*5 # so total iteration in grid cv will be 75

75

In [35]:
#### Fit the grid_search to the data
rf=RandomForestClassifier()
grid_search=GridSearchCV(estimator=rf,param_grid=param_grid,cv=10,n_jobs=-1,verbose=2)#n jobs means the cores njobs -1 means use all the cores of cpu
#verbose is the description or details of each task completed and thier time of completion 
grid_search.fit(X_train,y_train)


Fitting 10 folds for each of 75 candidates, totalling 750 fits


GridSearchCV(cv=10, estimator=RandomForestClassifier(), n_jobs=-1,
             param_grid={'criterion': ['gini'], 'max_depth': [450],
                         'max_features': ['auto'],
                         'min_samples_leaf': [1, 3, 5],
                         'min_samples_split': [3, 4, 5, 6, 7],
                         'n_estimators': [1600, 1700, 1800, 1900, 2000]},
             verbose=2)

In [36]:
best_grid=grid_search.best_estimator_

In [37]:
best_grid

RandomForestClassifier(max_depth=450, min_samples_split=3, n_estimators=1700)

In [38]:
y_pred=best_grid.predict(X_test)
print(confusion_matrix(y_test,y_pred))
print("Accuracy Score {}".format(accuracy_score(y_test,y_pred)))
print("Classification report: {}".format(classification_report(y_test,y_pred)))

[[95 12]
 [14 33]]
Accuracy Score 0.8311688311688312
Classification report:               precision    recall  f1-score   support

           0       0.87      0.89      0.88       107
           1       0.73      0.70      0.72        47

    accuracy                           0.83       154
   macro avg       0.80      0.79      0.80       154
weighted avg       0.83      0.83      0.83       154



### Automated Hyperparameter Tuning
Automated Hyperparameter Tuning can be done by using techniques such as 
- Bayesian Optimization
- Gradient Descent
- Evolutionary Algorithms

#### Bayesian Optimization
Bayesian optimization uses probability to find the minimum of a function. The final aim is to find the input value to a function which can gives us the lowest possible output value.It usually performs better than random,grid and manual search providing better performance in the testing phase and reduced optimization time.
In Hyperopt, Bayesian Optimization can be implemented giving 3 three main parameters to the function fmin.

- Objective Function = defines the loss function to minimize.
- Domain Space = defines the range of input values to test (in Bayesian Optimization this space creates a probability distribution for each of the used Hyperparameters).
- Optimization Algorithm = defines the search algorithm to use to select the best input values to use in each new iteration.

In [39]:
from hyperopt import hp,fmin,tpe,STATUS_OK,Trials
#hp is used whether selected range is int,float,string
#trial will be responsible in minimizing the function 
#fmin will be responsible in minimizing the values

In [40]:
#Domain space
space = {'criterion': hp.choice('criterion', ['entropy', 'gini']),#hp.choice emeans this has 2 parameters so it will choose best one
        'max_depth': hp.quniform('max_depth', 10, 1200, 10),#hp.quniform select integer value between the range of paarmeters we defined
        'max_features': hp.choice('max_features', ['auto', 'sqrt','log2', None]),
        'min_samples_leaf': hp.uniform('min_samples_leaf', 0, 0.5),#hp.uniform is to select range of numbers in float
        'min_samples_split' : hp.uniform ('min_samples_split', 0, 1),
        'n_estimators' : hp.choice('n_estimators', [10, 50, 300, 750, 1200,1300,1500])
    }

In [41]:
space

{'criterion': <hyperopt.pyll.base.Apply at 0x14a25dbc250>,
 'max_depth': <hyperopt.pyll.base.Apply at 0x14a25dbd060>,
 'max_features': <hyperopt.pyll.base.Apply at 0x14a25dbd180>,
 'min_samples_leaf': <hyperopt.pyll.base.Apply at 0x14a25dbcb80>,
 'min_samples_split': <hyperopt.pyll.base.Apply at 0x14a25dbd5a0>,
 'n_estimators': <hyperopt.pyll.base.Apply at 0x14a25dbd4b0>}

In [43]:
from sklearn.model_selection import cross_val_score
def objective(space):#function
    model = RandomForestClassifier(criterion = space['criterion'], max_depth = space['max_depth'],
                                 max_features = space['max_features'],
                                 min_samples_leaf = space['min_samples_leaf'],
                                 min_samples_split = space['min_samples_split'],
                                 n_estimators = space['n_estimators'], 
                                 )#optimization algo
    
    accuracy = cross_val_score(model, X_train, y_train, cv = 5).mean()

    # We aim to maximize accuracy, therefore we return it as a negative value
    return {'loss': -accuracy, 'status': STATUS_OK }

In [44]:

trials = Trials()#reduces or minimizes function
best = fmin(fn= objective, #reduces or minimizes values
            space= space,
            algo= tpe.suggest,#tpe.suggest it will suggest the optimization algo that we use in our case it is random forest
            max_evals = 80,
            trials= trials)
best

100%|███████████████████████████████████████████████| 80/80 [09:17<00:00,  6.97s/trial, best loss: -0.7638144742103159]


{'criterion': 1,
 'max_depth': 220.0,
 'max_features': 2,
 'min_samples_leaf': 0.08427447126012595,
 'min_samples_split': 0.289304252439954,
 'n_estimators': 6}

In [45]:
#WE MAP OUR VARIABLE BECAUSE WHEN U RUN BEST['CRITERION'] YOU WILL GET 1 INSTEAD WHAT WE WANT GINI OR ENTROPY SO WE MAP 0 1 VALUES WITH OUR ACTUAL VALUES WE WANT LIKE HERE IT IS 1:gini.c
crit = {0: 'entropy', 1: 'gini'}
feat = {0: 'auto', 1: 'sqrt', 2: 'log2', 3: None}
est = {0: 10, 1: 50, 2: 300, 3: 750, 4: 1200,5:1300,6:1500}


print(crit[best['criterion']])
print(feat[best['max_features']])
print(est[best['n_estimators']])

gini
log2
1500


In [46]:
best['min_samples_leaf']

0.08427447126012595

In [47]:
trainedforest = RandomForestClassifier(criterion = crit[best['criterion']], max_depth = best['max_depth'], 
                                       max_features = feat[best['max_features']], 
                                       min_samples_leaf = best['min_samples_leaf'], 
                                       min_samples_split = best['min_samples_split'], 
                                       n_estimators = est[best['n_estimators']]).fit(X_train,y_train)
predictionforest = trainedforest.predict(X_test)
print(confusion_matrix(y_test,predictionforest))
print(accuracy_score(y_test,predictionforest))
print(classification_report(y_test,predictionforest))
acc5 = accuracy_score(y_test,predictionforest)

[[97 10]
 [25 22]]
0.7727272727272727
              precision    recall  f1-score   support

           0       0.80      0.91      0.85       107
           1       0.69      0.47      0.56        47

    accuracy                           0.77       154
   macro avg       0.74      0.69      0.70       154
weighted avg       0.76      0.77      0.76       154



#### Genetic Algorithms 
Genetic Algorithms tries to apply natural selection mechanisms to Machine Learning contexts.

Let's immagine we create a population of N Machine Learning models with some predifined Hyperparameters. We can then calculate the accuracy of each model and decide to keep just half of the models (the ones that performs best). We can now generate some offsprings having similar Hyperparameters to the ones of the best models so that go get again a population of N models. At this point we can again caltulate the accuracy of each model and repeate the cycle for a defined number of generations. In this way, just the best models will survive at the end of the process.

In [48]:
#genetic chooses top performing models out of models we selectrd and make offspring that mdels or u can say child with similar values or parameters
#now with a example i am a offspring of my great grandfather and my father also so maybe the habits of my great grandfather will be in my grandfather then my dad them me so tahts why we call it genetic algorithmn
import numpy as np
from sklearn.model_selection import RandomizedSearchCV
# Number of trees in random forest
n_estimators = [int(x) for x in np.linspace(start = 200, stop = 2000, num = 10)]
# Number of features to consider at every split
max_features = ['auto', 'sqrt','log2']
# Maximum number of levels in tree
max_depth = [int(x) for x in np.linspace(10, 1000,10)]
# Minimum number of samples required to split a node
min_samples_split = [2, 5, 10,14]
# Minimum number of samples required at each leaf node
min_samples_leaf = [1, 2, 4,6,8]
# Create the random grid
param = {'n_estimators': n_estimators,
               'max_features': max_features,
               'max_depth': max_depth,
               'min_samples_split': min_samples_split,
               'min_samples_leaf': min_samples_leaf,
              'criterion':['entropy','gini']}
print(param)

{'n_estimators': [200, 400, 600, 800, 1000, 1200, 1400, 1600, 1800, 2000], 'max_features': ['auto', 'sqrt', 'log2'], 'max_depth': [10, 120, 230, 340, 450, 560, 670, 780, 890, 1000], 'min_samples_split': [2, 5, 10, 14], 'min_samples_leaf': [1, 2, 4, 6, 8], 'criterion': ['entropy', 'gini']}


In [ ]:
from tpot import TPOTClassifier #required tensorflow to run


tpot_classifier = TPOTClassifier(generations= 5, population_size= 24, offspring_size= 12,
                                 verbosity= 2, early_stop= 12,
                                 config_dict={'sklearn.ensemble.RandomForestClassifier': param}, #in this parameter you have to define which algo to use
                                 cv = 4, scoring = 'accuracy')
tpot_classifier.fit(X_train,y_train)

In [ ]:
accuracy = tpot_classifier.score(X_test, y_test)
print(accuracy)

### Optimize hyperparameters of the model using Optuna

The hyperparameters of the above algorithm are `n_estimators` and `max_depth` for which we can try different values to see if the model accuracy can be improved. The `objective` function is modified to accept a trial object. This trial has several methods for sampling hyperparameters. We create a study to run the hyperparameter optimization and finally read the best hyperparameters.

In [ ]:
 #For single algorithmn when we are not choosing between condition
    #n_estimators = trial.suggest_int('n_estimators', 200, 2000,10)
    #max_depth = int(trial.suggest_float('max_depth', 10, 100, log=True))
    #return sklearn.model_selection.cross_val_score(
        #clf,X_train,y_train, n_jobs=-1, cv=3).mean()

In [58]:
import optuna
import sklearn.svm
def objective(trial):#first we define an objective function ,trial is used to provide parameters that are used in hyper parameter for eg n estimator or maxdept

    classifier = trial.suggest_categorical('classifier', ['RandomForest', 'SVC'])#this we use when we want to choose between algorithms otherwise we directly name algo like below in clf variable we do below
   

   
    if classifier == 'RandomForest':
        n_estimators = trial.suggest_int('n_estimators', 200, 2000,10)
        max_depth = int(trial.suggest_float('max_depth', 10, 100, log=True))

        clf = sklearn.ensemble.RandomForestClassifier(
            n_estimators=n_estimators, max_depth=max_depth)
    else:
        c = trial.suggest_float('svc_c', 1e-10, 1e10, log=True)
        
        clf = sklearn.svm.SVC(C=c, gamma='auto')

    return sklearn.model_selection.cross_val_score(
        clf,X_train,y_train, n_jobs=-1, cv=3).mean()


In [59]:
study = optuna.create_study(direction='maximize')#create study will actually give the bigger space where training will happen use to maximize the accuracy find best hyper parameter
study.optimize(objective, n_trials=100)# now here we r optimizing the maximum accuracy ,n_trial is no of trials or iteration we gonna perform
trial = study.best_trial#getting best trial

print('Accuracy: {}'.format(trial.value)) #accuracy is present in trial.value
print("Best hyperparameters: {}".format(trial.params))#best hyperparameter is present trial.params

[I 2022-01-30 04:30:21,522] A new study created in memory with name: no-name-d08b1dc1-2f82-4c0d-8c5f-811d82408f0d
[I 2022-01-30 04:30:27,794] Trial 0 finished with value: 0.7508050374621393 and parameters: {'classifier': 'RandomForest', 'n_estimators': 810, 'max_depth': 31.348163791565014}. Best is trial 0 with value: 0.7508050374621393.
[I 2022-01-30 04:30:29,146] Trial 1 finished with value: 0.640068547744301 and parameters: {'classifier': 'SVC', 'svc_c': 9.263698630838596e-07}. Best is trial 0 with value: 0.7508050374621393.
[I 2022-01-30 04:30:29,218] Trial 2 finished with value: 0.640068547744301 and parameters: {'classifier': 'SVC', 'svc_c': 176785.17646085419}. Best is trial 0 with value: 0.7508050374621393.
[I 2022-01-30 04:30:29,338] Trial 3 finished with value: 0.640068547744301 and parameters: {'classifier': 'SVC', 'svc_c': 9383099835.999996}. Best is trial 0 with value: 0.7508050374621393.
[I 2022-01-30 04:30:34,315] Trial 4 finished with value: 0.7410250278973378 and param

[I 2022-01-30 04:32:17,317] Trial 35 finished with value: 0.7524390243902439 and parameters: {'classifier': 'RandomForest', 'n_estimators': 870, 'max_depth': 69.63703100869576}. Best is trial 12 with value: 0.7556751155746851.
[I 2022-01-30 04:32:17,437] Trial 36 finished with value: 0.640068547744301 and parameters: {'classifier': 'SVC', 'svc_c': 5627550986.2809105}. Best is trial 12 with value: 0.7556751155746851.
[I 2022-01-30 04:32:22,117] Trial 37 finished with value: 0.7475450342738722 and parameters: {'classifier': 'RandomForest', 'n_estimators': 1370, 'max_depth': 46.73074488059959}. Best is trial 12 with value: 0.7556751155746851.
[I 2022-01-30 04:32:24,845] Trial 38 finished with value: 0.7491630798660928 and parameters: {'classifier': 'RandomForest', 'n_estimators': 820, 'max_depth': 76.43877692882351}. Best is trial 12 with value: 0.7556751155746851.
[I 2022-01-30 04:32:24,997] Trial 39 finished with value: 0.640068547744301 and parameters: {'classifier': 'SVC', 'svc_c': 20

[I 2022-01-30 04:34:03,856] Trial 70 finished with value: 0.7459190180137095 and parameters: {'classifier': 'RandomForest', 'n_estimators': 310, 'max_depth': 16.11356316865976}. Best is trial 67 with value: 0.7589351187629524.
[I 2022-01-30 04:34:04,600] Trial 71 finished with value: 0.7508050374621393 and parameters: {'classifier': 'RandomForest', 'n_estimators': 220, 'max_depth': 11.070538732437106}. Best is trial 67 with value: 0.7589351187629524.
[I 2022-01-30 04:34:08,640] Trial 72 finished with value: 0.7475290929379882 and parameters: {'classifier': 'RandomForest', 'n_estimators': 1280, 'max_depth': 13.176807016829715}. Best is trial 67 with value: 0.7589351187629524.
[I 2022-01-30 04:34:12,504] Trial 73 finished with value: 0.7475530049418141 and parameters: {'classifier': 'RandomForest', 'n_estimators': 1150, 'max_depth': 11.436241114793308}. Best is trial 67 with value: 0.7589351187629524.
[I 2022-01-30 04:34:13,744] Trial 74 finished with value: 0.744285031085605 and paramet

Accuracy: 0.7589510600988363
Best hyperparameters: {'classifier': 'RandomForest', 'n_estimators': 1430, 'max_depth': 19.023859421808204}


In [60]:
trial

FrozenTrial(number=83, values=[0.7589510600988363], datetime_start=datetime.datetime(2022, 1, 30, 4, 34, 44, 49273), datetime_complete=datetime.datetime(2022, 1, 30, 4, 34, 48, 881395), params={'classifier': 'RandomForest', 'n_estimators': 1430, 'max_depth': 19.023859421808204}, distributions={'classifier': CategoricalDistribution(choices=('RandomForest', 'SVC')), 'n_estimators': IntUniformDistribution(high=2000, low=200, step=10), 'max_depth': LogUniformDistribution(high=100.0, low=10.0)}, user_attrs={}, system_attrs={}, intermediate_values={}, trial_id=83, state=TrialState.COMPLETE, value=None)

In [61]:
study.best_params

{'classifier': 'RandomForest',
 'n_estimators': 1430,
 'max_depth': 19.023859421808204}

In [63]:
rf=RandomForestClassifier(n_estimators=1430,max_depth=19)
rf.fit(X_train,y_train)

RandomForestClassifier(max_depth=19, n_estimators=1430)

In [64]:
y_pred=rf.predict(X_test)
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[95 12]
 [13 34]]
0.8376623376623377
              precision    recall  f1-score   support

           0       0.88      0.89      0.88       107
           1       0.74      0.72      0.73        47

    accuracy                           0.84       154
   macro avg       0.81      0.81      0.81       154
weighted avg       0.84      0.84      0.84       154

